using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Diagnostics;

using OSSim.Components;
using Scheduler = OSSim.Components.Scheduler;
// Release Notes:
//Tested in the following resolutions:
//      1920 x 1080
//      3840 x 2160
// Changing the scaling of the display(100%-125%) may also help in other resolutions.
// A tooltip was added to the parts of the program that are hard to see in some resolutions.
//
// 200 ms is the current lower limit for time units.
// The program still works with smaller time units, but the visuals lag behind the simulation.

// Entry point for the program
// General layout:
//          App.config - config file for the program
//          Components - background classes
//          UI - GUI elements
//          Properties - Sets working dir to solution dir to keep csv file with the project
// *.Desisgner.cs are automatically generated by the C# gui designer.
// *.resx are resource files, also automatically added with UI components but mostly unused
namespace OSSim
{
    static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            // WinForms API setup.
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainWindow());

        }



    }
}
